Added hidden empty file so that res will be created on checkout.
This fixes the following error message when initially building ion-test:
ERROR: resource directory $WORKSPACE'/ion-test/res' does not exist